name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Verify Docker Hub Credentials
        run: echo ${{ secrets.DOCKER_USERNAME }} && echo ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t shanukafer98/ranhuya-backend .
      - name: Publish Image to docker hub
        run: docker push shanukafer98/ranhuya-backend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull shanukafer98/ranhuya-backend:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nodejs-app-container -e MONGO='${{ secrets.MONGO }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}' shanukafer98/ranhuya-backend
